name: Deploy Laravel Application to Production Server
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4

    - name: Install Composer Dependencies
      run: composer install --optimize-autoloader --no-dev --no-progress --no-interaction --prefer-dist

    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Synchronize Files To Server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: "."
        REMOTE_HOST: ${{ secrets.STOCK_HOST }}
        REMOTE_USER: ${{ secrets.STOCK_USER }}
        TARGET: "/var/www/html/stock"
        RSYNC_OPTIONS: "--archive --compress --delete --verbose --rsh='ssh -i /home/runner/work/stock-inventory-monitoring/stock-inventory-monitoring/deploy_key -o StrictHostKeyChecking=no'"

    - name: Run Remote/Artisan Commands
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.STOCK_HOST }}
        username: ${{ secrets.STOCK_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/html/stock
          php artisan optimize