name: Publish to docker

on:    
  release:
      types: [published]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses:  actions/checkout@master
    - name: Publish to Registry (Latest Release)
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        php-version: '7.3'
        name: nuserv/stock-inventory-monitoring/tim:latest
        username: ${{ github.actor }}
        password:  ${{secrets.NUSERV_REGISTRY_DOCKER}}
        registry: docker.pkg.github.com
    - uses: actions/checkout@master
    - name: Publish to Registry (Version Release)
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nuserv/stock-inventory-monitoring/tim
        username: ${{ github.actor }}
        password: ${{secrets.NUSERV_REGISTRY_DOCKER}}
        registry: docker.pkg.github.com
        tag_names: true
