name: Publish to docker

on:    
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses:  actions/checkout@master
    - name: Publish to Registry (Latest Release)
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nuserv/stock-inventory-monitoring/tim:latest
        username: ${{ github.actor }}
        password: 8da33e7da3161892d2212c230f1f19bdd7a3e9d9
        registry: docker.pkg.github.com
    - uses: actions/checkout@master
    - name: Publish to Registry (Version Release)
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nuserv/stock-inventory-monitoring/tim
        username: ${{ github.actor }}
        password: 8da33e7da3161892d2212c230f1f19bdd7a3e9d9
        registry: docker.pkg.github.com
        tag_names: true