name: Publish to docker

on:    
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses:  actions/checkout@master
    - name: Publish to Registry (Latest Release)
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nuserv/stock-inventory-monitoring/tim:latest
        username: ${{ github.actor }}
        password:  4cc03c3ba9e808c529bcac491b2a02860f9fc28c
        registry: docker.pkg.github.com
    - uses: actions/checkout@master
    - name: Publish to Registry (Version Release)
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nuserv/stock-inventory-monitoring/tim
        username: ${{ github.actor }}
        password: 4cc03c3ba9e808c529bcac491b2a02860f9fc28c
        registry: docker.pkg.github.com
        tag_names: true